---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "# Java Simple QuickStart\r\n\r\nThis quickstarts run in a Java standalone\
      \ container using the jar style.\r\n\r\nThis example is implemented using very\
      \ simple Java code.\r\nThe source code is provided in the following java file\
      \ `src/main/java/io/fabric8/quickstarts/java/simple/Main.java`,\r\nwhich can\
      \ be viewed from [github](https://github.com/fabric8io/ipaas-quickstarts/blob/master/quickstart/java/simple-mainclass/src/main/java/io/fabric8/quickstarts/java/simple/Main.java).\r\
      \n\r\nThis example is printing *Hello Fabric8! Here's your random string: lRaNR*\
      \ to the standard output in the infinite loop.\r\n\r\n\r\n### Building\r\n\r\
      \nNavigate to the $IPAAS_QUICKSTART/quickstart/java/simple-mainclass/ folder\
      \ and the example can be built with\r\n\r\n    mvn clean install\r\n\r\n\r\n\
      ### Running the example locally\r\n\r\nThe example can be run locally using\
      \ the following Maven goal:\r\n\r\n    mvn exec:java\r\n\r\n\r\n### Running\
      \ the example in fabric8\r\n\r\nIt is assumed a running Kubernetes platform\
      \ is already running. If not you can find details how to [get started](http://fabric8.io/guide/getStarted/index.html).\r\
      \n\r\nThe example can be built and deployed using a single goal:\r\n\r\n   \
      \ mvn -Pf8-local-deploy\r\n\r\nWhen the example runs in fabric8, you can use\
      \ the OpenShift client tool to inspect the status\r\n\r\nTo list all the running\
      \ pods:\r\n\r\n    oc get pods\r\n\r\nThen find the name of the pod that runs\
      \ this quickstart, and output the logs from the running pods with:\r\n\r\n \
      \   oc logs <name of pod>\r\n\r\nYou can also use the fabric8 [web console](http://fabric8.io/guide/console.html)\
      \ to manage the\r\nrunning pods, and view logs and much more.\r\n\r\n\r\n###\
      \ More details\r\n\r\nYou can find more details about running this [quickstart](http://fabric8.io/guide/quickstarts/running.html)\
      \ on the website. This also includes instructions how to change the Docker image\
      \ user and registry.\r\n\r\n"
    fabric8.mall/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8/master/fabric8-maven-plugin/src/main/resources/icons/java.svg"
    fabric8.mall/summary: "Simple standalone Java Container (main class)"
  labels: {}
  name: "mall"
objects:
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "master"
      fabric8.io/git-commit: "dec4633ecc15f55cbfc4fc76a2796ebf1a0c8516"
    labels:
      container: "java"
      component: "mall"
      provider: "fabric8"
      project: "mall"
      version: "1.0-SNAPSHOT"
      group: "quickstarts"
    name: "mall"
  spec:
    replicas: 1
    selector:
      container: "java"
      component: "mall"
      provider: "fabric8"
      project: "mall"
      version: "1.0-SNAPSHOT"
      group: "quickstarts"
    template:
      metadata:
        annotations: {}
        labels:
          container: "java"
          component: "mall"
          provider: "fabric8"
          project: "mall"
          version: "1.0-SNAPSHOT"
          group: "quickstarts"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/mall:1.0-SNAPSHOT"
          name: "mall"
          ports:
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
